# Generated by Django 4.0.4 on 2022-05-29 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invsys_back', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='batch_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='requesition',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
