# Generated by Django 4.0.4 on 2022-05-29 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invsys_back', '0002_batch_batch_name_requesition_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesition',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='invsys_back.batch'),
        ),
    ]
