# Generated by Django 4.0.4 on 2022-05-29 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invsys_back', '0003_requesition_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requesition',
            name='is_approved',
        ),
    ]
