# Generated by Django 4.0.4 on 2022-05-29 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invsys_back', '0004_remove_requesition_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
