# Generated by Django 4.0.4 on 2022-05-29 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invsys_back', '0005_batch_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
