# Generated by Django 4.0.4 on 2022-05-31 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invsys_back', '0006_alter_batch_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
