# Generated by Django 4.0.4 on 2022-05-31 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invsys_back', '0007_product_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='requesition',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
